name: reversible_bloc
description: A bloc mixin that enables to rollback states.
version: 0.0.2
homepage: https://github.com/Gabanelli/reversible_bloc

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  bloc_test: ^9.0.3
  equatable: ^2.0.3

flutter: